Web3 API added. Types generation script updated to handle Web3 API spec design.
1inch/1inch-sdk-go pull request #75
Opened 2024-08-14 03:54 UTC by Tanz0rz

2024-08-16 19:12 UTC, AliakseiM requested changes

2024-08-16 19:17 UTC, AliakseiM commented
Also, I see that version tags have not been updated for a long time. This will prevent SDK users from receiving the latest changes.
I'd suggest increasing version (minor, patch) with every PR.

2024-08-16 20:39 UTC, Tanz0rz commented on codegen/openapi/web3-openapi.json
> +                    "type": "string",
Right now, for type generation, we are limited to what [oapi-codegen](https://github.com/oapi-codegen/oapi-codegen) supports. It does not handle `oneOf` properly for some reason. We tried other codegen tools and this tool got us the closest to what we want to use it for, so we need to work around its limitations for now. I have started a doc that I will eventually circulate to all the API teams internally so we can normalize our openapi spec generation. Right now, each openapi spec follows slightly different patterns and it causes a lot of issues with the type generation at the SDK level. That spec doc can be found [here](https://www.notion.so/1inch/OpenAPI-Spec-Guidelines-c1e0d03ec8e34aa4af30d3129f266cb4).

2024-08-16 20:40 UTC, Tanz0rz commented
> Also, I see that version tags have not been updated for a long time. This will prevent SDK users from receiving the latest changes. I'd suggest increasing version (minor, patch) with every PR.

The API was originally released with a different base design. What you are seeing now is the final steps of the refactor to change the design of the SDK entirely. Once we officially release this version, we will start doing semver updates. I think updating it with every PR makes a lot of sense.

2024-08-22 14:33 UTC, AliakseiM submitted a review, later dismissed

2024-08-22 21:55 UTC, merged